test_batch_size: 100
batch_size: 256
num_microbatches: 256
lr: 0.05
momentum: 0.5
decay: 0
S: 1
z: 1.1
dp: True
epochs: 120
save_on_epochs: [10, 50, 100, 200]
save_model: False
scheduler: False
useTF: False
